alias rvm-prompt=$HOME/.rvm/bin/rvm-prompt

# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh
ZSH_THEME="gnzh"

[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm"

COMPLETION_WAITING_DOTS="true"

plugins=(git osx rails ruby rvm cap bundler brew rake)
source $ZSH/oh-my-zsh.sh

export PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/X11/bin:/usr/texbin

PATH=$PATH:$HOME/bin
PATH=$PATH:/usr/local/share/npm/bin

export EDITOR="vim"

# Teamocil autocomplete
compctl -g '~/.teamocil/*(:t:r)' teamocil

source "$HOME/.scm_breeze/scm_breeze.sh"
